version: '3.1'

services:
  testdb:
    image: mysql:8.4
    container_name: testdb
    profiles: [test, debug]
    env_file: database/devdb.env
    ports:
      - "52000:52000"
    volumes:
      - "../docker-entrypoint-initdb.d/001-database-model.sql:/docker-entrypoint-initdb.d/01.sql"
      - "../docker-entrypoint-initdb.d/002-database-state-insert.sql:/docker-entrypoint-initdb.d/02.sql"
  debugpma:
    image: phpmyadmin:5
    container_name: debugpma
    profiles: [debug]
    environment:
      PMA_HOST: testdb
      PMA_PORT: 52000
      PMA_ARBITRARY: 1
      MYSQ_USER: demouser
      MYSQL_USER_PASSWORD: demopswd
    ports:
      - "8080:80"
    depends_on:
      - "testdb"
