version: '3.1'

services:
  testdb:
    image: mysql:8.4
    container_name: testdb
    profiles: [test]
    env_file: database/devdb.env
    ports:
      - "52000:52000"
    volumes:
      - "../docker-entrypoint-initdb.d/001-database-model.sql:/docker-entrypoint-initdb.d/01.sql"
      - "../docker-entrypoint-initdb.d/002-database-state-insert.sql:/docker-entrypoint-initdb.d/02.sql"
